// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyjeykiayvetbreouaio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5amV5a2lheXZldGJyZW91YWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTc5MzEsImV4cCI6MjA2NzAzMzkzMX0.ZCx9s8NKIVpipNusRznQi8yqgdRtMIh_uLXeeMkvCt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});